# -*- coding: utf-8 -*-
"""projetinho

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpbVP3LjHuoWpx44pWhCGxkinLXrVxJ7
"""

print(1)

a = 6
b = 2
op = a + b
print(op)

idade = int(input("digite sua idade: "))

if  idade <= 10:
  print("criança")
else:
  print("adolecente")

